server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:mysql://${DB_HOST}/${HOTEL_DB}?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: hotel-service
#  config:
#    import: configserver:http://localhost:8087
  config:
    import: configserver:http://cloud-config-server-svc.default.svc.cluster.local:80
  profiles:
    active: dev

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka








