server:
  port: 8084

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Little2001#
    url: jdbc:mysql://localhost:3306/microrating
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: rating-service
  config:
    import: configserver:http://localhost:8087
  profiles:
    active: dev

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka